### ISSUE TITLE
Link to the book isn't working

### ISSUE THREAD

**Issue by Ashkewww** [DS-AI-GATE/dsai-gate#8]
#bug 

[Algorithm Design : Jon Kleinberg and Eva Tardos](https://web.cs.ucla.edu/~srinath/static/pdfs/AlgorithmDesign_%20EvaTardos.pdf)

This link isn't working anymore. It shows this when you try to go to it.

![image](https://github.com/DS-AI-GATE/dsai-gate/assets/86144055/4e10fbfa-bcff-4d68-8cf5-7f6b46a0b1ca)

**Comment by functionalweeb** [comment]
Are you still preparing for DA?

**Comment by Kunaldargan** [comment]
Thank you for pointing out.
